name: benchmark

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Benchmark
        run: |
          curl -sL https://github.com/${GITHUB_REPOSITORY}/raw/master/README.md | \
          awk '{if($0 ~ "// go test -v"){a=1;b=1};if($0 ~ "```" && b=1){b=0};if (a&&b) {print}}' | \
          tee log_test.go
          go get github.com/${GITHUB_REPOSITORY}
          go get github.com/rs/zerolog
          go get go.uber.org/zap
          head -1 log_test.go | cut -b3- | sed -E 's#\r##' | bash -xe
